### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by strawberry-flavored-milk** [2022OSS-Team-Project/teamproject#1]
팀 주제를 선정하고자 합니다.

우선 저는 도서관 도서 관리 시스템, 자판기 관리 시스템을 생각해 보았어요!

**Comment by JeongSuA0724** [comment]
저는 헬스장 회원 관리 시스템, 소비 습관 저장을 통한 소비 습관 개선 시스템, 물류 코드 분류 시스템 생각해봤습니다!

**Comment by strawberry-flavored-milk** [comment]
헬스장, 물류 코드 좋은 것 같습니다! 둘 중 하나로 진행하고 싶은데 어떠신가요?

**Comment by JeongSuA0724** [comment]
넵 좋습니다! 제가 깃허브 알람이 안울려서 이제 확인 했습니다 ㅜㅜ 제가 오늘 새벽에 제가 할 수 있는 데까지 작업하고 업데이트 해두겠습니다 :)

**Comment by JeongSuA0724** [comment]
넵 좋습니다! 제가 깃허브 알람이 안울려서 이제 확인 했습니다 ㅜㅜ 제가 오늘 새벽에 제가 할 수 있는 데까지 작업하고 업데이트 해두겠습니다 :)
+ 헬스장 회원 관리 시스템을 만들어서 회원들의 인바디나 추천 운동이나 현재 몸 상태를 알려주는 기능을 추가하면 좋을 것 같은데 어떻게 생각하시나요??

**Comment by JeongSuA0724** [comment]
CRUD, 회원 데이터 파일 저장, 회원 데이터 파일 불러오기, 회원 데이터 검색 함수 (몸무게, 키, 이름, 나이 등으로 검색), 추천 운동 출력 함수, 키 대비 몸무게에 대한 추천 식단 출력 함수, 회원 등록 날짜 이용해서 남은 기간 확인하는 함수 등으로 생각해봤습니다! 아이디어 있으시면 업데이트 부탁드려요!

**Comment by strawberry-flavored-milk** [comment]
> CRUD, 회원 데이터 파일 저장, 회원 데이터 파일 불러오기, 회원 데이터 검색 함수 (몸무게, 키, 이름, 나이 등으로 검색), 추천 운동 출력 함수, 키 대비 몸무게에 대한 추천 식단 출력 함수, 회원 등록 날짜 이용해서 남은 기간 확인하는 함수 등으로 생각해봤습니다! 아이디어 있으시면 업데이트 부탁드려요!

좋습니다! 추천 운동 출력 함수도 조건문 이용해서 키, 몸무게, 근육량 등에 따라 다르게 출력하도록 하면 좋겠습니다!
함수들은 적어주신 것들로 가면 될 것 같아요
