### ISSUE TITLE
구현할 함수에 관하여

### ISSUE THREAD

**Issue by strawberry-flavored-milk** [2022OSS-Team-Project/teamproject#2]
CRUD, 데이터 파일 저장, 불러오기, 검색 함수는 일단 포함시키면 될 것 같습니다.
그러면 위의 함수는 총 7개인데, 10개 이상의 함수를 정의해야 합디다.
아이디어 있으면 공유해주시면 감사하겠습니다 :)

**Comment by JeongSuA0724** [comment]
우선 주제 선정을 먼저 하고 그에 어울리는 함수를 정하는 게 나을 것 같아서 주제를 먼저 선정하는 것이 어떨까요??
