### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by strawberry-flavored-milk** [2022OSS-Team-Project/teamproject#3]
역할 분담을 어떻게 해야 할 지에 대한 의견 부탁드립니다!
당장 떠오르는 건 함수 구현 분담(총 10+@개의 함수를 반씩 나누어 담당)인데, 추가하면 좋을 것이 있을까요?

**Comment by JeongSuA0724** [comment]
저도 함수 구현을 각자 반씩 나누어 맡는 것 이외는 잘 생각이 나지 않습니다.. 저희 둘 다 해야 하는 것은 서로 구현한 함수 피드백, 코드 수정 등등 디테일한 역할도 추가할까요?

**Comment by strawberry-flavored-milk** [comment]
네 그러면 서로의 함수 피드백 하는 것도 추가합시다!
