### ISSUE TITLE
헤더 파일 생성

### ISSUE THREAD

**Issue by JeongSuA0724** [2022OSS-Team-Project/teamproject#5]
학우님 첫번째 헤더 파일 생성해서 업데이트 했습니다!
확인 후 피드백 부탁 드립니다!

**Comment by strawberry-flavored-milk** [comment]
감사합니다 :)
#include ~ 는 .c 파일에서 쓰이니까 삭제해도 될 것 같습니다! 나머지 브분은 다 좋아요!

**Comment by strawberry-flavored-milk** [comment]
학우님이 생성하신 레포는 private이고 지금 이 레포에서 관련 issue들이 있어서 여기에 헤더파일 수정해서 올렸습니다! 확인 부탁드려요~
