### ISSUE TITLE
CRUD 분담 및 변수명 설정

### ISSUE THREAD

**Issue by strawberry-flavored-milk** [2022OSS-Team-Project/teamproject#8]
두 개씩 분담해서 구현하면 좋을 것 같습니다!
하고 싶은 거 있으면 적어주세요!
그리고 변수명도 통일해야 할 것 같아요. 필요한 변수가 뭐가 있을까요?

**Comment by JeongSuA0724** [comment]
int createInfo (Person *p);
void readInfo (Person *p);
int updateInfo (Person *p);
int deleteInfo (Person *p);
int saveInfoFile (Person *p);
int readInfoFile (Person *p);
int calculateInbody (Person *p);
int recommandDiet (Person *p);
int recommandExercise (Person *p);
int calculateExpirationDate (Person *p);

**Comment by JeongSuA0724** [comment]
CRUD랑 파일 관련 함수는 어떻게 나누면 좋을까요?

**Comment by strawberry-flavored-milk** [comment]
파일 관련 함수 분담은 아직 잘 모르겠습니다.
우선 이번 과제는 CRUD만 구현하면 되니까 이것만 생각하면 될 듯 해요!

**Comment by JeongSuA0724** [comment]
아아 CRUD 포함 모든 함수로 봤네요 ㅜㅜ 그러면 create, update 그리고 reading, delete 이렇게 하는 게 좋을 것 같은데 어떻게 생각하시나요?!

**Comment by JeongSuA0724** [comment]
변수명은 헤더에 있는 걸로 통일하면 될 것 같은데요..!!!

**Comment by JeongSuA0724** [comment]
혹시 더 필요한 변수가 생기면 다시 추가해서 의논하면 될 것 같아요!

**Comment by strawberry-flavored-milk** [comment]
아 제가 구조체를 제대로 안 봤네요ㅠㅠ
제가 delete 구현을 잘 못해서 제가 create랑 update해도 괜찮으신가요?

**Comment by JeongSuA0724** [comment]
네! 그럼 언제까지 해서 맞춰볼까요??

**Comment by strawberry-flavored-milk** [comment]
토요일에서 일요일로 넘어가는 자정까지 어떤가요?!

**Comment by JeongSuA0724** [comment]
네! 알겠습니당~ 그때 다시 연락 드릴게요~

**Comment by strawberry-flavored-milk** [comment]
넵 감사합니다 :)

**Comment by strawberry-flavored-milk** [comment]
Create, Read 구현하고 커밋했습니다! 제가 만든 파일에 Update랑  추가해주시면 될 것 같아요!

**Comment by strawberry-flavored-milk** [comment]
miniproject/inc 의 personal_info.c 가 함수를 정의한 파일이고, membership_management.c가 메인 파일입니다

**Comment by strawberry-flavored-milk** [comment]
아 그리고 피드백 있으면 해주시면 감사하겠습니다!

**Comment by JeongSuA0724** [comment]
Create update 파일 구현하시기로 한 거 아니었나요?!?!

**Comment by strawberry-flavored-milk** [comment]
아 실수했네요.. 그냥 제가 update도 만들어놓을까요?

**Comment by JeongSuA0724** [comment]
제가 나머지 두개 create read 변수 보고 만들겠습니다 ㅎㅎ 그대신 내일 일어나셔서 확인할 수 있으시게 자정 좀 넘은 시간에 업데이트 가능할 것 같은데 괜찮으신가요?!

**Comment by JeongSuA0724** [comment]
저도 올해 복학이라 실력이 뛰어난 건 아니라서.. 좀 시간이 걸려요..ㅜㅜ 그래도 일어나셔서 바로 확인하실 수 있게끔 구현해두겠습니다!

**Comment by strawberry-flavored-milk** [comment]
실력이 뛰어나지 않다니 기만하시는 기술이 좋으시네요! 서두르실 필요 없으니까 천천히 하세요 :)
